import type { NextApiRequest, NextApiResponse } from 'next';
import nodemailer from 'nodemailer';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  const { name, email, message } = req.body;

  if (!name || !email || !message) {
    return res.status(400).json({ message: 'Missing fields' });
  }

  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  const mailOptions = {
    from: `"Portfolio Sitem" <${process.env.SMTP_USER}>`,
    to: 'site@baturayduman.com', // Target address requested
    replyTo: email,
    subject: `New Contact Request | ${name}`,
    html: `
      <div style="font-family: 'Inter', sans-serif; max-width: 600px; margin: 0 auto; background-color: #030706; padding: 40px; border-radius: 16px; color: #F0FDF4; border: 1px solid rgba(255, 255, 255, 0.08);">
        <h2 style="color: #2DD4BF; border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 15px; margin-top: 0;">New Contact Submission</h2>
        
        <div style="margin-top: 30px;">
          <p style="margin: 0 0 10px 0; font-size: 14px; color: #9CA3AF;"><strong>Name:</strong></p>
          <p style="margin: 0 0 20px 0; font-size: 16px;">${name}</p>
          
          <p style="margin: 0 0 10px 0; font-size: 14px; color: #9CA3AF;"><strong>Email:</strong></p>
          <p style="margin: 0 0 20px 0; font-size: 16px;">
            <a href="mailto:${email}" style="color: #2DD4BF; text-decoration: none;">${email}</a>
          </p>
          
          <p style="margin: 0 0 10px 0; font-size: 14px; color: #9CA3AF;"><strong>Message:</strong></p>
          <div style="background-color: rgba(255, 255, 255, 0.04); padding: 20px; border-radius: 8px; font-size: 15px; line-height: 1.6;">
            ${message.replace(/\n/g, '<br>')}
          </div>
        </div>
        
        <div style="margin-top: 40px; text-align: center; font-size: 12px; color: #6B7280; border-top: 1px solid rgba(255,255,255,0.08); padding-top: 20px;">
          This email was securely generated by your Portfolio Application.
        </div>
      </div>
    `,
  };

  try {
    if (!process.env.SMTP_USER) {
        console.warn('SMTP credentials not configured. Skipping actual email send.');
        return res.status(200).json({ message: 'Success (development test, no mail sent)' });
    }

    await transporter.sendMail(mailOptions);
    res.status(200).json({ message: 'Success' });
  } catch (error) {
    console.error('SMTP Error:', error);
    res.status(500).json({ message: 'Error sending email' });
  }
}
